// Crack The Coding Interview - Dinesh Varyani
// Source: https://docs.google.com/spreadsheets/d/1pnI8HmSMPcfwrCCu7wYETCXaKDig4VucZDpcjVRuYrE
// 500 curated LeetCode problems with topic tags and difficulty

export interface CTCIProblem {
  id: number;
  name: string;
  url: string;
  topic: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
}

export const CTCI_PROBLEMS: CTCIProblem[] = [
  { id: 1, name: "Two Sum", url: "https://leetcode.com/problems/two-sum", topic: "Array, Hash Table", difficulty: "Easy" },
  { id: 2, name: "Longest Substring Without Repeating Characters", url: "https://leetcode.com/problems/longest-substring-without-repeating-characters", topic: "Hash Table, String, Sliding Window", difficulty: "Medium" },
  { id: 3, name: "Maximum Subarray", url: "https://leetcode.com/problems/maximum-subarray", topic: "Array, Divide and Conquer, Dynamic Programming", difficulty: "Medium" },
  { id: 4, name: "Valid Anagram", url: "https://leetcode.com/problems/valid-anagram", topic: "Hash Table, String, Sorting", difficulty: "Easy" },
  { id: 5, name: "Reverse Linked List", url: "https://leetcode.com/problems/reverse-linked-list", topic: "Linked List, Recursion", difficulty: "Easy" },
  { id: 6, name: "3Sum", url: "https://leetcode.com/problems/3sum", topic: "Array, Two Pointers, Sorting", difficulty: "Medium" },
  { id: 7, name: "Longest Palindromic Substring", url: "https://leetcode.com/problems/longest-palindromic-substring", topic: "String, Dynamic Programming", difficulty: "Medium" },
  { id: 8, name: "Median Of Two Sorted Arrays", url: "https://leetcode.com/problems/median-of-two-sorted-arrays", topic: "Array, Binary Search, Divide and Conquer", difficulty: "Hard" },
  { id: 9, name: "Container With Most Water", url: "https://leetcode.com/problems/container-with-most-water", topic: "Array, Two Pointers, Greedy", difficulty: "Medium" },
  { id: 10, name: "Best Time To Buy And Sell Stock", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock", topic: "Array, Dynamic Programming", difficulty: "Easy" },
  { id: 11, name: "Search In Rotated Sorted Array", url: "https://leetcode.com/problems/search-in-rotated-sorted-array", topic: "Array, Binary Search", difficulty: "Medium" },
  { id: 12, name: "Number Of Islands", url: "https://leetcode.com/problems/number-of-islands", topic: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", difficulty: "Medium" },
  { id: 13, name: "Lru Cache", url: "https://leetcode.com/problems/lru-cache", topic: "Hash Table, Linked List, Design, Doubly-Linked List", difficulty: "Medium" },
  { id: 14, name: "Merge Intervals", url: "https://leetcode.com/problems/merge-intervals", topic: "Array, Sorting", difficulty: "Medium" },
  { id: 15, name: "Generate Parentheses", url: "https://leetcode.com/problems/generate-parentheses", topic: "String, Dynamic Programming, Backtracking", difficulty: "Medium" },
  { id: 16, name: "Find The Duplicate Number", url: "https://leetcode.com/problems/find-the-duplicate-number", topic: "Array, Two Pointers, Binary Search, Bit Manipulation", difficulty: "Medium" },
  { id: 17, name: "Product Of Array Except Self", url: "https://leetcode.com/problems/product-of-array-except-self", topic: "Array, Prefix Sum", difficulty: "Medium" },
  { id: 18, name: "Valid Parentheses", url: "https://leetcode.com/problems/valid-parentheses", topic: "String, Stack", difficulty: "Easy" },
  { id: 19, name: "Subarray Sum Equals K", url: "https://leetcode.com/problems/subarray-sum-equals-k", topic: "Array, Hash Table, Prefix Sum", difficulty: "Medium" },
  { id: 20, name: "House Robber", url: "https://leetcode.com/problems/house-robber", topic: "Array, Dynamic Programming", difficulty: "Medium" },
  { id: 21, name: "Longest Increasing Subsequence", url: "https://leetcode.com/problems/longest-increasing-subsequence", topic: "Array, Binary Search, Dynamic Programming", difficulty: "Medium" },
  { id: 22, name: "Reverse Linked List", url: "https://leetcode.com/problems/reverse-linked-list", topic: "Linked List, Recursion", difficulty: "Easy" },
  { id: 23, name: "Maximum Product Subarray", url: "https://leetcode.com/problems/maximum-product-subarray", topic: "Array, Dynamic Programming", difficulty: "Medium" },
  { id: 24, name: "Merge K Sorted Lists", url: "https://leetcode.com/problems/merge-k-sorted-lists", topic: "Linked List, Divide and Conquer, Heap (Priority Queue), Merge Sort", difficulty: "Hard" },
  { id: 25, name: "Merge Two Sorted Lists", url: "https://leetcode.com/problems/merge-two-sorted-lists", topic: "Linked List, Recursion", difficulty: "Easy" },
  { id: 26, name: "Climbing Stairs", url: "https://leetcode.com/problems/climbing-stairs", topic: "Math, Dynamic Programming, Memoization", difficulty: "Easy" },
  { id: 27, name: "Coin Change", url: "https://leetcode.com/problems/coin-change", topic: "Array, Dynamic Programming, Breadth-First Search", difficulty: "Medium" },
  { id: 28, name: "Jump Game", url: "https://leetcode.com/problems/jump-game", topic: "Array, Dynamic Programming, Greedy", difficulty: "Medium" },
  { id: 29, name: "Word Break", url: "https://leetcode.com/problems/word-break", topic: "Hash Table, String, Dynamic Programming, Trie, Memoization", difficulty: "Medium" },
  { id: 30, name: "Minimum Window Substring", url: "https://leetcode.com/problems/minimum-window-substring", topic: "Hash Table, String, Sliding Window", difficulty: "Hard" },
  { id: 31, name: "Find First And Last Position Of Element In Sorted Array", url: "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array", topic: "Array, Binary Search", difficulty: "Medium" },
  { id: 32, name: "Permutations", url: "https://leetcode.com/problems/permutations", topic: "Array, Backtracking", difficulty: "Medium" },
  { id: 33, name: "Combination Sum", url: "https://leetcode.com/problems/combination-sum", topic: "Array, Backtracking", difficulty: "Medium" },
  { id: 34, name: "Letter Combinations Of A Phone Number", url: "https://leetcode.com/problems/letter-combinations-of-a-phone-number", topic: "Hash Table, String, Backtracking", difficulty: "Medium" },
  { id: 35, name: "Validate Binary Search Tree", url: "https://leetcode.com/problems/validate-binary-search-tree", topic: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", difficulty: "Medium" },
  { id: 36, name: "Sliding Window Maximum", url: "https://leetcode.com/problems/sliding-window-maximum", topic: "Array, Queue, Sliding Window, Heap (Priority Queue), Monotonic Queue", difficulty: "Hard" },
  { id: 37, name: "Lowest Common Ancestor Of A Binary Tree", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree", topic: "Tree, Depth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 38, name: "Symmetric Tree", url: "https://leetcode.com/problems/symmetric-tree", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 39, name: "Next Permutation", url: "https://leetcode.com/problems/next-permutation", topic: "Array, Two Pointers", difficulty: "Medium" },
  { id: 40, name: "Sort Colors", url: "https://leetcode.com/problems/sort-colors", topic: "Array, Two Pointers, Sorting", difficulty: "Medium" },
  { id: 41, name: "Remove Nth Node From End Of List", url: "https://leetcode.com/problems/remove-nth-node-from-end-of-list", topic: "Linked List, Two Pointers", difficulty: "Medium" },
  { id: 42, name: "Single Number", url: "https://leetcode.com/problems/single-number", topic: "Array, Bit Manipulation", difficulty: "Easy" },
  { id: 43, name: "Largest Rectangle In Histogram", url: "https://leetcode.com/problems/largest-rectangle-in-histogram", topic: "Array, Stack, Monotonic Stack", difficulty: "Hard" },
  { id: 44, name: "First Missing Positive", url: "https://leetcode.com/problems/first-missing-positive", topic: "Array, Hash Table", difficulty: "Hard" },
  { id: 45, name: "Course Schedule", url: "https://leetcode.com/problems/course-schedule", topic: "Depth-First Search, Breadth-First Search, Graph, Topological Sort", difficulty: "Medium" },
  { id: 46, name: "Binary Tree Maximum Path Sum", url: "https://leetcode.com/problems/binary-tree-maximum-path-sum", topic: "Dynamic Programming, Tree, Depth-First Search, Binary Tree", difficulty: "Hard" },
  { id: 47, name: "Word Search", url: "https://leetcode.com/problems/word-search", topic: "Array, Backtracking, Matrix", difficulty: "Medium" },
  { id: 48, name: "Subsets", url: "https://leetcode.com/problems/subsets", topic: "Array, Backtracking, Bit Manipulation", difficulty: "Medium" },
  { id: 49, name: "Longest Consecutive Sequence", url: "https://leetcode.com/problems/longest-consecutive-sequence", topic: "Array, Hash Table, Union Find", difficulty: "Medium" },
  { id: 50, name: "Kth Largest Element In An Array", url: "https://leetcode.com/problems/kth-largest-element-in-an-array", topic: "Array, Divide and Conquer, Sorting, Heap (Priority Queue), Quickselect", difficulty: "Medium" },
  { id: 51, name: "Group Anagrams", url: "https://leetcode.com/problems/group-anagrams", topic: "Hash Table, String, Sorting", difficulty: "Medium" },
  { id: 52, name: "Move Zeroes", url: "https://leetcode.com/problems/move-zeroes", topic: "Array, Two Pointers", difficulty: "Easy" },
  { id: 53, name: "Intersection Of Two Linked Lists", url: "https://leetcode.com/problems/intersection-of-two-linked-lists", topic: "Hash Table, Linked List, Two Pointers", difficulty: "Easy" },
  { id: 54, name: "Majority Element", url: "https://leetcode.com/problems/majority-element", topic: "Array, Hash Table, Divide and Conquer, Sorting, Counting", difficulty: "Easy" },
  { id: 55, name: "Unique Paths", url: "https://leetcode.com/problems/unique-paths", topic: "Math, Dynamic Programming, Combinatorics", difficulty: "Medium" },
  { id: 56, name: "Rotate Image", url: "https://leetcode.com/problems/rotate-image", topic: "Array, Math, Matrix", difficulty: "Medium" },
  { id: 57, name: "Spiral Matrix", url: "https://leetcode.com/problems/spiral-matrix", topic: "Array, Matrix, Simulation", difficulty: "Medium" },
  { id: 58, name: "Set Matrix Zeroes", url: "https://leetcode.com/problems/set-matrix-zeroes", topic: "Array, Hash Table, Matrix", difficulty: "Medium" },
  { id: 59, name: "Decode Ways", url: "https://leetcode.com/problems/decode-ways", topic: "String, Dynamic Programming", difficulty: "Medium" },
  { id: 60, name: "Linked List Cycle", url: "https://leetcode.com/problems/linked-list-cycle", topic: "Hash Table, Linked List, Two Pointers", difficulty: "Easy" },
  { id: 61, name: "Trapping Rain Water", url: "https://leetcode.com/problems/trapping-rain-water", topic: "Array, Two Pointers, Dynamic Programming, Stack, Monotonic Stack", difficulty: "Hard" },
  { id: 62, name: "Min Stack", url: "https://leetcode.com/problems/min-stack", topic: "Stack, Design", difficulty: "Medium" },
  { id: 63, name: "Implement Trie Prefix Tree", url: "https://leetcode.com/problems/implement-trie-prefix-tree", topic: "Hash Table, String, Design, Trie", difficulty: "Medium" },
  { id: 64, name: "Find Median From Data Stream", url: "https://leetcode.com/problems/find-median-from-data-stream", topic: "Two Pointers, Design, Sorting, Heap (Priority Queue), Data Stream", difficulty: "Hard" },
  { id: 65, name: "Binary Tree Level Order Traversal", url: "https://leetcode.com/problems/binary-tree-level-order-traversal", topic: "Tree, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 66, name: "Maximum Depth Of Binary Tree", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 67, name: "Invert Binary Tree", url: "https://leetcode.com/problems/invert-binary-tree", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 68, name: "Path Sum", url: "https://leetcode.com/problems/path-sum", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 69, name: "Diameter Of Binary Tree", url: "https://leetcode.com/problems/diameter-of-binary-tree", topic: "Tree, Depth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 70, name: "Flatten Binary Tree To Linked List", url: "https://leetcode.com/problems/flatten-binary-tree-to-linked-list", topic: "Linked List, Stack, Tree, Depth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 71, name: "Serialize And Deserialize Binary Tree", url: "https://leetcode.com/problems/serialize-and-deserialize-binary-tree", topic: "String, Tree, Depth-First Search, Breadth-First Search, Design, Binary Tree", difficulty: "Hard" },
  { id: 72, name: "Construct Binary Tree From Preorder And Inorder Traversal", url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal", topic: "Array, Hash Table, Divide and Conquer, Tree, Binary Tree", difficulty: "Medium" },
  { id: 73, name: "Populating Next Right Pointers In Each Node", url: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node", topic: "Linked List, Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 74, name: "Count Complete Tree Nodes", url: "https://leetcode.com/problems/count-complete-tree-nodes", topic: "Binary Search, Tree, Depth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 75, name: "Kth Smallest Element In A Bst", url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst", topic: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", difficulty: "Medium" },
  { id: 76, name: "Number Of 1 Bits", url: "https://leetcode.com/problems/number-of-1-bits", topic: "Divide and Conquer, Bit Manipulation", difficulty: "Easy" },
  { id: 77, name: "Reverse Bits", url: "https://leetcode.com/problems/reverse-bits", topic: "Divide and Conquer, Bit Manipulation", difficulty: "Easy" },
  { id: 78, name: "Missing Number", url: "https://leetcode.com/problems/missing-number", topic: "Array, Hash Table, Math, Binary Search, Bit Manipulation, Sorting", difficulty: "Easy" },
  { id: 79, name: "Counting Bits", url: "https://leetcode.com/problems/counting-bits", topic: "Dynamic Programming, Bit Manipulation", difficulty: "Easy" },
  { id: 80, name: "Sum Of Two Integers", url: "https://leetcode.com/problems/sum-of-two-integers", topic: "Math, Bit Manipulation", difficulty: "Medium" },
  { id: 81, name: "Top K Frequent Elements", url: "https://leetcode.com/problems/top-k-frequent-elements", topic: "Array, Hash Table, Divide and Conquer, Sorting, Heap (Priority Queue), Bucket Sort, Counting, Quickselect", difficulty: "Medium" },
  { id: 82, name: "Encode And Decode Strings", url: "https://leetcode.com/problems/encode-and-decode-strings", topic: "Array, String, Design", difficulty: "Medium" },
  { id: 83, name: "Longest Common Subsequence", url: "https://leetcode.com/problems/longest-common-subsequence", topic: "String, Dynamic Programming", difficulty: "Medium" },
  { id: 84, name: "Pacific Atlantic Water Flow", url: "https://leetcode.com/problems/pacific-atlantic-water-flow", topic: "Array, Depth-First Search, Breadth-First Search, Matrix", difficulty: "Medium" },
  { id: 85, name: "Non Overlapping Intervals", url: "https://leetcode.com/problems/non-overlapping-intervals", topic: "Array, Dynamic Programming, Greedy, Sorting", difficulty: "Medium" },
  { id: 86, name: "Meeting Rooms", url: "https://leetcode.com/problems/meeting-rooms", topic: "Array, Sorting", difficulty: "Easy" },
  { id: 87, name: "Meeting Rooms Ii", url: "https://leetcode.com/problems/meeting-rooms-ii", topic: "Array, Two Pointers, Greedy, Sorting, Heap (Priority Queue), Prefix Sum", difficulty: "Medium" },
  { id: 88, name: "Graph Valid Tree", url: "https://leetcode.com/problems/graph-valid-tree", topic: "Depth-First Search, Breadth-First Search, Union Find, Graph", difficulty: "Medium" },
  { id: 89, name: "Number Of Connected Components In An Undirected Graph", url: "https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph", topic: "Depth-First Search, Breadth-First Search, Union Find, Graph", difficulty: "Medium" },
  { id: 90, name: "Alien Dictionary", url: "https://leetcode.com/problems/alien-dictionary", topic: "Array, String, Depth-First Search, Breadth-First Search, Graph, Topological Sort", difficulty: "Hard" },
  { id: 91, name: "Clone Graph", url: "https://leetcode.com/problems/clone-graph", topic: "Hash Table, Depth-First Search, Breadth-First Search, Graph", difficulty: "Medium" },
  { id: 92, name: "Word Ladder", url: "https://leetcode.com/problems/word-ladder", topic: "Hash Table, String, Breadth-First Search", difficulty: "Hard" },
  { id: 93, name: "Network Delay Time", url: "https://leetcode.com/problems/network-delay-time", topic: "Depth-First Search, Breadth-First Search, Graph, Heap (Priority Queue), Shortest Path", difficulty: "Medium" },
  { id: 94, name: "Cheapest Flights Within K Stops", url: "https://leetcode.com/problems/cheapest-flights-within-k-stops", topic: "Dynamic Programming, Depth-First Search, Breadth-First Search, Graph, Heap (Priority Queue), Shortest Path", difficulty: "Medium" },
  { id: 95, name: "Reconstruct Itinerary", url: "https://leetcode.com/problems/reconstruct-itinerary", topic: "Depth-First Search, Graph, Eulerian Circuit", difficulty: "Hard" },
  { id: 96, name: "Min Cost To Connect All Points", url: "https://leetcode.com/problems/min-cost-to-connect-all-points", topic: "Array, Union Find, Graph, Minimum Spanning Tree", difficulty: "Medium" },
  { id: 97, name: "Swim In Rising Water", url: "https://leetcode.com/problems/swim-in-rising-water", topic: "Array, Binary Search, Depth-First Search, Breadth-First Search, Union Find, Heap (Priority Queue), Matrix", difficulty: "Hard" },
  { id: 98, name: "Walls And Gates", url: "https://leetcode.com/problems/walls-and-gates", topic: "Array, Breadth-First Search, Matrix", difficulty: "Medium" },
  { id: 99, name: "Rotting Oranges", url: "https://leetcode.com/problems/rotting-oranges", topic: "Array, Breadth-First Search, Matrix", difficulty: "Medium" },
  { id: 100, name: "Surrounded Regions", url: "https://leetcode.com/problems/surrounded-regions", topic: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", difficulty: "Medium" },
  { id: 101, name: "House Robber Iii", url: "https://leetcode.com/problems/house-robber-iii", topic: "Dynamic Programming, Tree, Depth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 102, name: "Sort List", url: "https://leetcode.com/problems/sort-list", topic: "Linked List, Two Pointers, Divide and Conquer, Sorting, Merge Sort", difficulty: "Medium" },
  { id: 103, name: "Find All Anagrams In A String", url: "https://leetcode.com/problems/find-all-anagrams-in-a-string", topic: "Hash Table, String, Sliding Window", difficulty: "Medium" },
  { id: 104, name: "Binary Tree Right Side View", url: "https://leetcode.com/problems/binary-tree-right-side-view", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 105, name: "Palindromic Substrings", url: "https://leetcode.com/problems/palindromic-substrings", topic: "String, Dynamic Programming", difficulty: "Medium" },
  { id: 106, name: "Maximum Depth Of Binary Tree", url: "https://leetcode.com/problems/maximum-depth-of-binary-tree", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 107, name: "Rotting Oranges", url: "https://leetcode.com/problems/rotting-oranges", topic: "Array, Breadth-First Search, Matrix", difficulty: "Medium" },
  { id: 108, name: "Set Matrix Zeroes", url: "https://leetcode.com/problems/set-matrix-zeroes", topic: "Array, Hash Table, Matrix", difficulty: "Medium" },
  { id: 109, name: "Convert Sorted Array To Binary Search Tree", url: "https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree", topic: "Array, Divide and Conquer, Tree, Binary Search Tree, Binary Tree", difficulty: "Easy" },
  { id: 110, name: "Search A 2d Matrix", url: "https://leetcode.com/problems/search-a-2d-matrix", topic: "Array, Binary Search, Matrix", difficulty: "Medium" },
  { id: 111, name: "Find Minimum In Rotated Sorted Array", url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array", topic: "Array, Binary Search", difficulty: "Medium" },
  { id: 112, name: "Populating Next Right Pointers In Each Node", url: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 113, name: "Remove Duplicates From Sorted Array", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array", topic: "Array, Two Pointers", difficulty: "Easy" },
  { id: 114, name: "Kth Smallest Element In A Bst", url: "https://leetcode.com/problems/kth-smallest-element-in-a-bst", topic: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", difficulty: "Medium" },
  { id: 115, name: "Minimum Size Subarray Sum", url: "https://leetcode.com/problems/minimum-size-subarray-sum", topic: "Array, Binary Search, Sliding Window, Prefix Sum", difficulty: "Medium" },
  { id: 116, name: "Find All Duplicates In An Array", url: "https://leetcode.com/problems/find-all-duplicates-in-an-array", topic: "Array, Hash Table", difficulty: "Medium" },
  { id: 117, name: "Burst Balloons", url: "https://leetcode.com/problems/burst-balloons", topic: "Array, Dynamic Programming", difficulty: "Hard" },
  { id: 118, name: "Counting Bits", url: "https://leetcode.com/problems/counting-bits", topic: "Dynamic Programming, Bit Manipulation", difficulty: "Easy" },
  { id: 119, name: "All Nodes Distance K In Binary Tree", url: "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 120, name: "Swap Nodes In Pairs", url: "https://leetcode.com/problems/swap-nodes-in-pairs", topic: "Linked List, Recursion", difficulty: "Medium" },
  { id: 121, name: "Reverse Linked List Ii", url: "https://leetcode.com/problems/reverse-linked-list-ii", topic: "Linked List", difficulty: "Medium" },
  { id: 122, name: "Word Search Ii", url: "https://leetcode.com/problems/word-search-ii", topic: "Array, String, Backtracking, Trie, Matrix", difficulty: "Hard" },
  { id: 123, name: "Longest Common Subsequence", url: "https://leetcode.com/problems/longest-common-subsequence", topic: "String, Dynamic Programming", difficulty: "Medium" },
  { id: 124, name: "Kth Smallest Element In A Sorted Matrix", url: "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix", topic: "Array, Binary Search, Sorting, Heap (Priority Queue), Matrix", difficulty: "Medium" },
  { id: 125, name: "4sum", url: "https://leetcode.com/problems/4sum", topic: "Array, Two Pointers, Sorting", difficulty: "Medium" },
  { id: 126, name: "Best Time To Buy And Sell Stock Iii", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii", topic: "Array, Dynamic Programming", difficulty: "Hard" },
  { id: 127, name: "Best Time To Buy And Sell Stock With Cooldown", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown", topic: "Array, Dynamic Programming", difficulty: "Medium" },
  { id: 128, name: "Palindrome Partitioning", url: "https://leetcode.com/problems/palindrome-partitioning", topic: "String, Dynamic Programming, Backtracking", difficulty: "Medium" },
  { id: 129, name: "Reorder List", url: "https://leetcode.com/problems/reorder-list", topic: "Linked List, Two Pointers, Stack, Recursion", difficulty: "Medium" },
  { id: 130, name: "Min Cost Climbing Stairs", url: "https://leetcode.com/problems/min-cost-climbing-stairs", topic: "Array, Dynamic Programming", difficulty: "Easy" },
  { id: 131, name: "Max Area Of Island", url: "https://leetcode.com/problems/max-area-of-island", topic: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", difficulty: "Medium" },
  { id: 132, name: "Count Of Smaller Numbers After Self", url: "https://leetcode.com/problems/count-of-smaller-numbers-after-self", topic: "Array, Binary Search, Divide and Conquer, Binary Indexed Tree, Segment Tree, Merge Sort, Ordered Set", difficulty: "Hard" },
  { id: 133, name: "3sum Closest", url: "https://leetcode.com/problems/3sum-closest", topic: "Array, Two Pointers, Sorting", difficulty: "Medium" },
  { id: 134, name: "Binary Tree Zigzag Level Order Traversal", url: "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal", topic: "Tree, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 135, name: "Find Peak Element", url: "https://leetcode.com/problems/find-peak-element", topic: "Array, Binary Search", difficulty: "Medium" },
  { id: 136, name: "Insert Delete Getrandom O1", url: "https://leetcode.com/problems/insert-delete-getrandom-o1", topic: "Array, Hash Table, Math, Design, Randomized", difficulty: "Medium" },
  { id: 137, name: "Balanced Binary Tree", url: "https://leetcode.com/problems/balanced-binary-tree", topic: "Tree, Depth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 138, name: "Palindrome Number", url: "https://leetcode.com/problems/palindrome-number", topic: "Math", difficulty: "Easy" },
  { id: 139, name: "N Queens", url: "https://leetcode.com/problems/n-queens", topic: "Array, Backtracking", difficulty: "Hard" },
  { id: 140, name: "K Closest Points To Origin", url: "https://leetcode.com/problems/k-closest-points-to-origin", topic: "Array, Math, Divide and Conquer, Geometry, Sorting, Heap (Priority Queue), Quickselect", difficulty: "Medium" },
  { id: 141, name: "Odd Even Linked List", url: "https://leetcode.com/problems/odd-even-linked-list", topic: "Linked List", difficulty: "Medium" },
  { id: 142, name: "Minimum Height Trees", url: "https://leetcode.com/problems/minimum-height-trees", topic: "Depth-First Search, Breadth-First Search, Graph, Topological Sort", difficulty: "Medium" },
  { id: 143, name: "Same Tree", url: "https://leetcode.com/problems/same-tree", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 144, name: "Lowest Common Ancestor Of A Binary Search Tree", url: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree", topic: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", difficulty: "Easy" },
  { id: 145, name: "Shortest Unsorted Continuous Subarray", url: "https://leetcode.com/problems/shortest-unsorted-continuous-subarray", topic: "Array, Two Pointers, Stack, Greedy, Sorting, Monotonic Stack", difficulty: "Medium" },
  { id: 146, name: "Binary Search Tree Iterator", url: "https://leetcode.com/problems/binary-search-tree-iterator", topic: "Stack, Tree, Design, Binary Search Tree, Binary Tree, Iterator", difficulty: "Medium" },
  { id: 147, name: "Longest Increasing Path In A Matrix", url: "https://leetcode.com/problems/longest-increasing-path-in-a-matrix", topic: "Dynamic Programming, Depth-First Search, Breadth-First Search, Graph, Topological Sort, Memoization", difficulty: "Hard" },
  { id: 148, name: "Queue Reconstruction By Height", url: "https://leetcode.com/problems/queue-reconstruction-by-height", topic: "Array, Greedy, Sorting", difficulty: "Medium" },
  { id: 149, name: "Path Sum", url: "https://leetcode.com/problems/path-sum", topic: "Tree, Depth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 150, name: "Delete Node In A Bst", url: "https://leetcode.com/problems/delete-node-in-a-bst", topic: "Tree, Binary Search Tree, Binary Tree", difficulty: "Medium" },
  { id: 151, name: "Subtree Of Another Tree", url: "https://leetcode.com/problems/subtree-of-another-tree", topic: "Tree, Depth-First Search, String Matching, Binary Tree, Hash Function", difficulty: "Easy" },
  { id: 152, name: "Missing Number", url: "https://leetcode.com/problems/missing-number", topic: "Array, Hash Table, Math, Bit Manipulation, Sorting", difficulty: "Easy" },
  { id: 153, name: "Longest Palindromic Subsequence", url: "https://leetcode.com/problems/longest-palindromic-subsequence", topic: "String, Dynamic Programming", difficulty: "Medium" },
  { id: 154, name: "Evaluate Division", url: "https://leetcode.com/problems/evaluate-division", topic: "Array, Depth-First Search, Breadth-First Search, Union Find, Graph, Shortest Path", difficulty: "Medium" },
  { id: 155, name: "House Robber Ii", url: "https://leetcode.com/problems/house-robber-ii", topic: "Array, Dynamic Programming", difficulty: "Medium" },
  { id: 156, name: "Pascals Triangle", url: "https://leetcode.com/problems/pascals-triangle", topic: "Array, Dynamic Programming", difficulty: "Easy" },
  { id: 157, name: "Clone Graph", url: "https://leetcode.com/problems/clone-graph", topic: "Hash Table, Depth-First Search, Breadth-First Search, Graph", difficulty: "Medium" },
  { id: 158, name: "Coin Change 2", url: "https://leetcode.com/problems/coin-change-2", topic: "Array, Dynamic Programming", difficulty: "Medium" },
  { id: 159, name: "Happy Number", url: "https://leetcode.com/problems/happy-number", topic: "Hash Table, Math, Two Pointers", difficulty: "Easy" },
  { id: 160, name: "Number Of Provinces", url: "https://leetcode.com/problems/number-of-provinces", topic: "Depth-First Search, Breadth-First Search, Union Find, Graph", difficulty: "Medium" },
  { id: 161, name: "Single Element In A Sorted Array", url: "https://leetcode.com/problems/single-element-in-a-sorted-array", topic: "Array, Binary Search", difficulty: "Medium" },
  { id: 162, name: "Gas Station", url: "https://leetcode.com/problems/gas-station", topic: "Array, Greedy", difficulty: "Medium" },
  { id: 163, name: "Unique Binary Search Trees Ii", url: "https://leetcode.com/problems/unique-binary-search-trees-ii", topic: "Dynamic Programming, Backtracking, Tree, Binary Search Tree, Binary Tree", difficulty: "Medium" },
  { id: 164, name: "Cheapest Flights Within K Stops", url: "https://leetcode.com/problems/cheapest-flights-within-k-stops", topic: "Dynamic Programming, Depth-First Search, Breadth-First Search, Graph, Heap (Priority Queue), Shortest Path", difficulty: "Medium" },
  { id: 165, name: "Middle Of The Linked List", url: "https://leetcode.com/problems/middle-of-the-linked-list", topic: "Linked List, Two Pointers", difficulty: "Easy" },
  { id: 166, name: "Remove K Digits", url: "https://leetcode.com/problems/remove-k-digits", topic: "String, Stack, Greedy, Monotonic Stack", difficulty: "Medium" },
  { id: 167, name: "Sudoku Solver", url: "https://leetcode.com/problems/sudoku-solver", topic: "Array, Backtracking, Matrix", difficulty: "Hard" },
  { id: 168, name: "Surrounded Regions", url: "https://leetcode.com/problems/surrounded-regions", topic: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", difficulty: "Medium" },
  { id: 169, name: "Count Complete Tree Nodes", url: "https://leetcode.com/problems/count-complete-tree-nodes", topic: "Binary Search, Tree, Depth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 170, name: "Remove Invalid Parentheses", url: "https://leetcode.com/problems/remove-invalid-parentheses", topic: "String, Backtracking, Breadth-First Search", difficulty: "Hard" },
  { id: 171, name: "Partition To K Equal Sum Subsets", url: "https://leetcode.com/problems/partition-to-k-equal-sum-subsets", topic: "Array, Dynamic Programming, Backtracking, Bit Manipulation, Memoization, Bitmask", difficulty: "Medium" },
  { id: 172, name: "Two Sum Ii Input Array Is Sorted", url: "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted", topic: "Array, Two Pointers, Binary Search", difficulty: "Easy" },
  { id: 173, name: "First Unique Character In A String", url: "https://leetcode.com/problems/first-unique-character-in-a-string", topic: "Hash Table, String, Queue, Counting", difficulty: "Easy" },
  { id: 174, name: "Largest Number", url: "https://leetcode.com/problems/largest-number", topic: "String, Greedy, Sorting", difficulty: "Medium" },
  { id: 175, name: "Count Primes", url: "https://leetcode.com/problems/count-primes", topic: "Array, Math, Enumeration, Number Theory", difficulty: "Medium" },
  { id: 176, name: "Squares Of A Sorted Array", url: "https://leetcode.com/problems/squares-of-a-sorted-array", topic: "Array, Two Pointers, Sorting", difficulty: "Easy" },
  { id: 177, name: "Permutations Ii", url: "https://leetcode.com/problems/permutations-ii", topic: "Array, Backtracking", difficulty: "Medium" },
  { id: 178, name: "Word Break Ii", url: "https://leetcode.com/problems/word-break-ii", topic: "Hash Table, String, Dynamic Programming, Backtracking, Trie, Memoization", difficulty: "Hard" },
  { id: 179, name: "Combination Sum Ii", url: "https://leetcode.com/problems/combination-sum-ii", topic: "Array, Backtracking", difficulty: "Medium" },
  { id: 180, name: "Triangle", url: "https://leetcode.com/problems/triangle", topic: "Array, Dynamic Programming", difficulty: "Medium" },
  { id: 181, name: "Remove Linked List Elements", url: "https://leetcode.com/problems/remove-linked-list-elements", topic: "Linked List, Recursion", difficulty: "Easy" },
  { id: 182, name: "Remove Duplicates From Sorted List Ii", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii", topic: "Linked List, Two Pointers", difficulty: "Medium" },
  { id: 183, name: "Valid Sudoku", url: "https://leetcode.com/problems/valid-sudoku", topic: "Array, Hash Table, Matrix", difficulty: "Medium" },
  { id: 184, name: "Path Sum Ii", url: "https://leetcode.com/problems/path-sum-ii", topic: "Backtracking, Tree, Depth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 185, name: "Convert Sorted List To Binary Search Tree", url: "https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree", topic: "Linked List, Divide and Conquer, Tree, Binary Search Tree, Binary Tree", difficulty: "Medium" },
  { id: 186, name: "Insert Interval", url: "https://leetcode.com/problems/insert-interval", topic: "Array", difficulty: "Medium" },
  { id: 187, name: "Wildcard Matching", url: "https://leetcode.com/problems/wildcard-matching", topic: "String, Dynamic Programming, Greedy, Recursion", difficulty: "Hard" },
  { id: 188, name: "Subsets Ii", url: "https://leetcode.com/problems/subsets-ii", topic: "Array, Backtracking, Bit Manipulation", difficulty: "Medium" },
  { id: 189, name: "Unique Paths Ii", url: "https://leetcode.com/problems/unique-paths-ii", topic: "Array, Dynamic Programming, Matrix", difficulty: "Medium" },
  { id: 190, name: "Split Array Largest Sum", url: "https://leetcode.com/problems/split-array-largest-sum", topic: "Array, Binary Search, Dynamic Programming, Greedy", difficulty: "Hard" },
  { id: 191, name: "Reorganize String", url: "https://leetcode.com/problems/reorganize-string", topic: "Hash Table, String, Greedy, Sorting, Heap (Priority Queue), Counting", difficulty: "Medium" },
  { id: 192, name: "Permutation In String", url: "https://leetcode.com/problems/permutation-in-string", topic: "Hash Table, Two Pointers, String, Sliding Window", difficulty: "Medium" },
  { id: 193, name: "Majority Element Ii", url: "https://leetcode.com/problems/majority-element-ii", topic: "Array, Hash Table, Sorting, Counting", difficulty: "Medium" },
  { id: 194, name: "Construct Binary Tree From Inorder And Postorder Traversal", url: "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal", topic: "Array, Hash Table, Divide and Conquer, Tree, Binary Tree", difficulty: "Medium" },
  { id: 195, name: "Minimum Cost For Tickets", url: "https://leetcode.com/problems/minimum-cost-for-tickets", topic: "Array, Dynamic Programming", difficulty: "Medium" },
  { id: 196, name: "Top K Frequent Words", url: "https://leetcode.com/problems/top-k-frequent-words", topic: "Hash Table, String, Trie, Sorting, Heap (Priority Queue), Bucket Sort, Counting", difficulty: "Medium" },
  { id: 197, name: "Island Perimeter", url: "https://leetcode.com/problems/island-perimeter", topic: "Array, Depth-First Search, Breadth-First Search, Matrix", difficulty: "Easy" },
  { id: 198, name: "Remove Duplicates From Sorted List", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-list", topic: "Linked List", difficulty: "Easy" },
  { id: 199, name: "Add Binary", url: "https://leetcode.com/problems/add-binary", topic: "Math, String, Bit Manipulation, Simulation", difficulty: "Easy" },
  { id: 200, name: "01 Matrix", url: "https://leetcode.com/problems/01-matrix", topic: "Array, Dynamic Programming, Breadth-First Search, Matrix", difficulty: "Medium" },
  { id: 201, name: "Valid Anagram", url: "https://leetcode.com/problems/valid-anagram", topic: "Hash Table, String, Sorting", difficulty: "Easy" },
  { id: 202, name: "Multiply Strings", url: "https://leetcode.com/problems/multiply-strings", topic: "Math, String, Simulation", difficulty: "Medium" },
  { id: 203, name: "First Bad Version", url: "https://leetcode.com/problems/first-bad-version", topic: "Binary Search, Interactive", difficulty: "Easy" },
  { id: 204, name: "Design Add And Search Words Data Structure", url: "https://leetcode.com/problems/design-add-and-search-words-data-structure", topic: "String, Depth-First Search, Design, Trie", difficulty: "Medium" },
  { id: 205, name: "Next Greater Element Ii", url: "https://leetcode.com/problems/next-greater-element-ii", topic: "Array, Stack, Monotonic Stack", difficulty: "Medium" },
  { id: 206, name: "Basic Calculator Ii", url: "https://leetcode.com/problems/basic-calculator-ii", topic: "Math, String, Stack", difficulty: "Medium" },
  { id: 207, name: "Accounts Merge", url: "https://leetcode.com/problems/accounts-merge", topic: "Array, String, Depth-First Search, Breadth-First Search, Union Find", difficulty: "Medium" },
  { id: 208, name: "Valid Palindrome Ii", url: "https://leetcode.com/problems/valid-palindrome-ii", topic: "Two Pointers, String, Greedy", difficulty: "Easy" },
  { id: 209, name: "Delete Node In A Linked List", url: "https://leetcode.com/problems/delete-node-in-a-linked-list", topic: "Linked List", difficulty: "Easy" },
  { id: 210, name: "Interval List Intersections", url: "https://leetcode.com/problems/interval-list-intersections", topic: "Array, Two Pointers", difficulty: "Medium" },
  { id: 211, name: "Rotate List", url: "https://leetcode.com/problems/rotate-list", topic: "Linked List, Two Pointers", difficulty: "Medium" },
  { id: 212, name: "Sum Root To Leaf Numbers", url: "https://leetcode.com/problems/sum-root-to-leaf-numbers", topic: "Tree, Depth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 213, name: "Dungeon Game", url: "https://leetcode.com/problems/dungeon-game", topic: "Array, Dynamic Programming, Matrix", difficulty: "Hard" },
  { id: 214, name: "Powx N", url: "https://leetcode.com/problems/powx-n", topic: "Math, Recursion", difficulty: "Medium" },
  { id: 215, name: "Max Consecutive Ones Iii", url: "https://leetcode.com/problems/max-consecutive-ones-iii", topic: "Array, Binary Search, Sliding Window, Prefix Sum", difficulty: "Medium" },
  { id: 216, name: "Intersection Of Two Arrays Ii", url: "https://leetcode.com/problems/intersection-of-two-arrays-ii", topic: "Array, Hash Table, Two Pointers, Binary Search, Sorting", difficulty: "Easy" },
  { id: 217, name: "Remove Duplicate Letters", url: "https://leetcode.com/problems/remove-duplicate-letters", topic: "String, Stack, Greedy, Monotonic Stack", difficulty: "Medium" },
  { id: 218, name: "Recover Binary Search Tree", url: "https://leetcode.com/problems/recover-binary-search-tree", topic: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", difficulty: "Medium" },
  { id: 219, name: "Is Graph Bipartite", url: "https://leetcode.com/problems/is-graph-bipartite", topic: "Depth-First Search, Breadth-First Search, Union Find, Graph", difficulty: "Medium" },
  { id: 220, name: "Contiguous Array", url: "https://leetcode.com/problems/contiguous-array", topic: "Array, Hash Table, Prefix Sum", difficulty: "Medium" },
  { id: 221, name: "Find K Closest Elements", url: "https://leetcode.com/problems/find-k-closest-elements", topic: "Array, Two Pointers, Binary Search, Sorting, Heap (Priority Queue)", difficulty: "Medium" },
  { id: 222, name: "Reverse String", url: "https://leetcode.com/problems/reverse-string", topic: "Two Pointers, String, Recursion", difficulty: "Easy" },
  { id: 223, name: "Range Sum Of Bst", url: "https://leetcode.com/problems/range-sum-of-bst", topic: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", difficulty: "Easy" },
  { id: 224, name: "Sort Characters By Frequency", url: "https://leetcode.com/problems/sort-characters-by-frequency", topic: "Hash Table, String, Sorting, Heap (Priority Queue), Bucket Sort, Counting", difficulty: "Medium" },
  { id: 225, name: "Longest Repeating Character Replacement", url: "https://leetcode.com/problems/longest-repeating-character-replacement", topic: "Hash Table, String, Sliding Window", difficulty: "Medium" },
  { id: 226, name: "Binary Tree Postorder Traversal", url: "https://leetcode.com/problems/binary-tree-postorder-traversal", topic: "Stack, Tree, Depth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 227, name: "Single Number Ii", url: "https://leetcode.com/problems/single-number-ii", topic: "Array, Bit Manipulation", difficulty: "Medium" },
  { id: 228, name: "Ugly Number Ii", url: "https://leetcode.com/problems/ugly-number-ii", topic: "Hash Table, Math, Dynamic Programming, Heap (Priority Queue)", difficulty: "Medium" },
  { id: 229, name: "Reconstruct Itinerary", url: "https://leetcode.com/problems/reconstruct-itinerary", topic: "Depth-First Search, Graph, Eulerian Circuit", difficulty: "Hard" },
  { id: 230, name: "The Skyline Problem", url: "https://leetcode.com/problems/the-skyline-problem", topic: "Array, Divide and Conquer, Binary Indexed Tree, Segment Tree, Line Sweep, Heap (Priority Queue), Ordered Set", difficulty: "Hard" },
  { id: 231, name: "Single Number Iii", url: "https://leetcode.com/problems/single-number-iii", topic: "Array, Bit Manipulation", difficulty: "Medium" },
  { id: 232, name: "Is Subsequence", url: "https://leetcode.com/problems/is-subsequence", topic: "Two Pointers, String, Dynamic Programming", difficulty: "Easy" },
  { id: 233, name: "Network Delay Time", url: "https://leetcode.com/problems/network-delay-time", topic: "Depth-First Search, Breadth-First Search, Graph, Heap (Priority Queue), Shortest Path", difficulty: "Medium" },
  { id: 234, name: "Binary Tree Paths", url: "https://leetcode.com/problems/binary-tree-paths", topic: "String, Tree, Depth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 235, name: "Longest Substring With At Least K Repeating Characters", url: "https://leetcode.com/problems/longest-substring-with-at-least-k-repeating-characters", topic: "Hash Table, String, Divide and Conquer, Sliding Window", difficulty: "Medium" },
  { id: 236, name: "Minimum Depth Of Binary Tree", url: "https://leetcode.com/problems/minimum-depth-of-binary-tree", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 237, name: "Best Time To Buy And Sell Stock With Transaction Fee", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee", topic: "Array, Dynamic Programming, Greedy", difficulty: "Medium" },
  { id: 238, name: "Non Decreasing Array", url: "https://leetcode.com/problems/non-decreasing-array", topic: "Array", difficulty: "Medium" },
  { id: 239, name: "Interleaving String", url: "https://leetcode.com/problems/interleaving-string", topic: "String, Dynamic Programming", difficulty: "Medium" },
  { id: 240, name: "Game Of Life", url: "https://leetcode.com/problems/game-of-life", topic: "Array, Matrix, Simulation", difficulty: "Medium" },
  { id: 241, name: "Combinations", url: "https://leetcode.com/problems/combinations", topic: "Array, Backtracking", difficulty: "Medium" },
  { id: 242, name: "Binary Tree Preorder Traversal", url: "https://leetcode.com/problems/binary-tree-preorder-traversal", topic: "Stack, Tree, Depth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 243, name: "All Paths From Source To Target", url: "https://leetcode.com/problems/all-paths-from-source-to-target", topic: "Backtracking, Depth-First Search, Breadth-First Search, Graph", difficulty: "Medium" },
  { id: 244, name: "Plus One", url: "https://leetcode.com/problems/plus-one", topic: "Array, Math", difficulty: "Easy" },
  { id: 245, name: "Best Time To Buy And Sell Stock Iv", url: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv", topic: "Array, Dynamic Programming", difficulty: "Hard" },
  { id: 246, name: "Increasing Triplet Subsequence", url: "https://leetcode.com/problems/increasing-triplet-subsequence", topic: "Array, Greedy", difficulty: "Medium" },
  { id: 247, name: "Trim A Binary Search Tree", url: "https://leetcode.com/problems/trim-a-binary-search-tree", topic: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", difficulty: "Medium" },
  { id: 248, name: "Backspace String Compare", url: "https://leetcode.com/problems/backspace-string-compare", topic: "Two Pointers, String, Stack, Simulation", difficulty: "Easy" },
  { id: 249, name: "Maximum Length Of Repeated Subarray", url: "https://leetcode.com/problems/maximum-length-of-repeated-subarray", topic: "Array, Binary Search, Dynamic Programming, Sliding Window, Rolling Hash, Hash Function", difficulty: "Medium" },
  { id: 250, name: "Capacity To Ship Packages Within D Days", url: "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days", topic: "Array, Binary Search, Greedy", difficulty: "Medium" },
  { id: 251, name: "Implement Strstr", url: "https://leetcode.com/problems/implement-strstr", topic: "Two Pointers, String, String Matching", difficulty: "Easy" },
  { id: 252, name: "Word Ladder Ii", url: "https://leetcode.com/problems/word-ladder-ii", topic: "Hash Table, String, Backtracking, Breadth-First Search", difficulty: "Hard" },
  { id: 253, name: "Subarray Product Less Than K", url: "https://leetcode.com/problems/subarray-product-less-than-k", topic: "Array, Sliding Window", difficulty: "Medium" },
  { id: 254, name: "Contains Duplicate", url: "https://leetcode.com/problems/contains-duplicate", topic: "Array, Hash Table, Sorting", difficulty: "Easy" },
  { id: 255, name: "Flatten A Multilevel Doubly Linked List", url: "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list", topic: "Linked List, Depth-First Search, Doubly-Linked List", difficulty: "Medium" },
  { id: 256, name: "Populating Next Right Pointers In Each Node Ii", url: "https://leetcode.com/problems/populating-next-right-pointers-in-each-node-ii", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 257, name: "Maximum Binary Tree", url: "https://leetcode.com/problems/maximum-binary-tree", topic: "Array, Divide and Conquer, Stack, Tree, Monotonic Stack, Binary Tree", difficulty: "Medium" },
  { id: 258, name: "Minimum Remove To Make Valid Parentheses", url: "https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses", topic: "String, Stack", difficulty: "Medium" },
  { id: 259, name: "Distribute Coins In Binary Tree", url: "https://leetcode.com/problems/distribute-coins-in-binary-tree", topic: "Tree, Depth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 260, name: "Critical Connections In A Network", url: "https://leetcode.com/problems/critical-connections-in-a-network", topic: "Depth-First Search, Graph, Biconnected Component", difficulty: "Hard" },
  { id: 261, name: "Basic Calculator", url: "https://leetcode.com/problems/basic-calculator", topic: "Math, String, Stack, Recursion", difficulty: "Hard" },
  { id: 262, name: "Redundant Connection", url: "https://leetcode.com/problems/redundant-connection", topic: "Depth-First Search, Breadth-First Search, Union Find, Graph", difficulty: "Medium" },
  { id: 263, name: "Jewels And Stones", url: "https://leetcode.com/problems/jewels-and-stones", topic: "Hash Table, String", difficulty: "Easy" },
  { id: 264, name: "Non Overlapping Intervals", url: "https://leetcode.com/problems/non-overlapping-intervals", topic: "Array, Dynamic Programming, Greedy, Sorting", difficulty: "Medium" },
  { id: 265, name: "Flood Fill", url: "https://leetcode.com/problems/flood-fill", topic: "Array, Depth-First Search, Breadth-First Search, Matrix", difficulty: "Easy" },
  { id: 266, name: "Zigzag Conversion", url: "https://leetcode.com/problems/zigzag-conversion", topic: "String", difficulty: "Medium" },
  { id: 267, name: "Maximum Width Of Binary Tree", url: "https://leetcode.com/problems/maximum-width-of-binary-tree", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 268, name: "Permutation Sequence", url: "https://leetcode.com/problems/permutation-sequence", topic: "Math, Recursion", difficulty: "Hard" },
  { id: 269, name: "Construct Binary Search Tree From Preorder Traversal", url: "https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal", topic: "Array, Stack, Tree, Binary Search Tree, Monotonic Stack, Binary Tree", difficulty: "Medium" },
  { id: 270, name: "Different Ways To Add Parentheses", url: "https://leetcode.com/problems/different-ways-to-add-parentheses", topic: "Math, String, Dynamic Programming, Recursion, Memoization", difficulty: "Medium" },
  { id: 271, name: "Search In Rotated Sorted Array Ii", url: "https://leetcode.com/problems/search-in-rotated-sorted-array-ii", topic: "Array, Binary Search", difficulty: "Medium" },
  { id: 272, name: "Add Two Numbers Ii", url: "https://leetcode.com/problems/add-two-numbers-ii", topic: "Linked List, Math, Stack", difficulty: "Medium" },
  { id: 273, name: "Two Sum Iv Input Is A Bst", url: "https://leetcode.com/problems/two-sum-iv-input-is-a-bst", topic: "Hash Table, Two Pointers, Tree, Depth-First Search, Breadth-First Search, Binary Search Tree, Binary Tree", difficulty: "Easy" },
  { id: 274, name: "Convert Bst To Greater Tree", url: "https://leetcode.com/problems/convert-bst-to-greater-tree", topic: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", difficulty: "Medium" },
  { id: 275, name: "Partition List", url: "https://leetcode.com/problems/partition-list", topic: "Linked List, Two Pointers", difficulty: "Medium" },
  { id: 276, name: "Sqrtx", url: "https://leetcode.com/problems/sqrtx", topic: "Math, Binary Search", difficulty: "Easy" },
  { id: 277, name: "Isomorphic Strings", url: "https://leetcode.com/problems/isomorphic-strings", topic: "Hash Table, String", difficulty: "Easy" },
  { id: 278, name: "Number Of Longest Increasing Subsequence", url: "https://leetcode.com/problems/number-of-longest-increasing-subsequence", topic: "Array, Dynamic Programming, Binary Indexed Tree, Segment Tree", difficulty: "Medium" },
  { id: 279, name: "Binary Search", url: "https://leetcode.com/problems/binary-search", topic: "Array, Binary Search", difficulty: "Easy" },
  { id: 280, name: "Valid Parenthesis String", url: "https://leetcode.com/problems/valid-parenthesis-string", topic: "String, Dynamic Programming, Stack, Greedy", difficulty: "Medium" },
  { id: 281, name: "Repeated Substring Pattern", url: "https://leetcode.com/problems/repeated-substring-pattern", topic: "String, String Matching", difficulty: "Easy" },
  { id: 282, name: "Remove Element", url: "https://leetcode.com/problems/remove-element", topic: "Array, Two Pointers", difficulty: "Easy" },
  { id: 283, name: "Combination Sum Iv", url: "https://leetcode.com/problems/combination-sum-iv", topic: "Array, Dynamic Programming", difficulty: "Medium" },
  { id: 284, name: "Distinct Subsequences", url: "https://leetcode.com/problems/distinct-subsequences", topic: "String, Dynamic Programming", difficulty: "Hard" },
  { id: 285, name: "Asteroid Collision", url: "https://leetcode.com/problems/asteroid-collision", topic: "Array, Stack", difficulty: "Medium" },
  { id: 286, name: "Largest Divisible Subset", url: "https://leetcode.com/problems/largest-divisible-subset", topic: "Array, Math, Dynamic Programming, Sorting", difficulty: "Medium" },
  { id: 287, name: "Pacific Atlantic Water Flow", url: "https://leetcode.com/problems/pacific-atlantic-water-flow", topic: "Array, Depth-First Search, Breadth-First Search, Matrix", difficulty: "Medium" },
  { id: 288, name: "132 Pattern", url: "https://leetcode.com/problems/132-pattern", topic: "Array, Binary Search, Stack, Monotonic Stack, Ordered Set", difficulty: "Medium" },
  { id: 289, name: "Delete And Earn", url: "https://leetcode.com/problems/delete-and-earn", topic: "Array, Hash Table, Dynamic Programming", difficulty: "Medium" },
  { id: 290, name: "Sum Of Subarray Minimums", url: "https://leetcode.com/problems/sum-of-subarray-minimums", topic: "Array, Dynamic Programming, Stack, Monotonic Stack", difficulty: "Medium" },
  { id: 291, name: "Count Square Submatrices With All Ones", url: "https://leetcode.com/problems/count-square-submatrices-with-all-ones", topic: "Array, Dynamic Programming, Matrix", difficulty: "Medium" },
  { id: 292, name: "Palindrome Partitioning Ii", url: "https://leetcode.com/problems/palindrome-partitioning-ii", topic: "String, Dynamic Programming", difficulty: "Hard" },
  { id: 293, name: "Sum Of Left Leaves", url: "https://leetcode.com/problems/sum-of-left-leaves", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 294, name: "Hamming Distance", url: "https://leetcode.com/problems/hamming-distance", topic: "Bit Manipulation", difficulty: "Easy" },
  { id: 295, name: "Flatten Nested List Iterator", url: "https://leetcode.com/problems/flatten-nested-list-iterator", topic: "Stack, Tree, Depth-First Search, Design, Queue, Iterator", difficulty: "Medium" },
  { id: 296, name: "Score Of Parentheses", url: "https://leetcode.com/problems/score-of-parentheses", topic: "String, Stack", difficulty: "Medium" },
  { id: 297, name: "Longest String Chain", url: "https://leetcode.com/problems/longest-string-chain", topic: "Array, Hash Table, Two Pointers, String, Dynamic Programming", difficulty: "Medium" },
  { id: 298, name: "Valid Palindrome", url: "https://leetcode.com/problems/valid-palindrome", topic: "Two Pointers, String", difficulty: "Easy" },
  { id: 299, name: "Longest Univalue Path", url: "https://leetcode.com/problems/longest-univalue-path", topic: "Tree, Depth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 300, name: "Letter Case Permutation", url: "https://leetcode.com/problems/letter-case-permutation", topic: "String, Backtracking, Bit Manipulation", difficulty: "Medium" },
  { id: 301, name: "Binary Tree Level Order Traversal Ii", url: "https://leetcode.com/problems/binary-tree-level-order-traversal-ii", topic: "Tree, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 302, name: "Find Duplicate Subtrees", url: "https://leetcode.com/problems/find-duplicate-subtrees", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 303, name: "Minimum Cost Tree From Leaf Values", url: "https://leetcode.com/problems/minimum-cost-tree-from-leaf-values", topic: "Dynamic Programming, Stack, Greedy, Monotonic Stack", difficulty: "Medium" },
  { id: 304, name: "Lfu Cache", url: "https://leetcode.com/problems/lfu-cache", topic: "Hash Table, Linked List, Design, Doubly-Linked List", difficulty: "Hard" },
  { id: 305, name: "Russian Doll Envelopes", url: "https://leetcode.com/problems/russian-doll-envelopes", topic: "Array, Binary Search, Dynamic Programming, Sorting", difficulty: "Hard" },
  { id: 306, name: "Maximum Profit In Job Scheduling", url: "https://leetcode.com/problems/maximum-profit-in-job-scheduling", topic: "Array, Binary Search, Dynamic Programming, Sorting", difficulty: "Hard" },
  { id: 307, name: "Add Strings", url: "https://leetcode.com/problems/add-strings", topic: "Math, String, Simulation", difficulty: "Easy" },
  { id: 308, name: "Pairs Of Songs With Total Durations Divisible By 60", url: "https://leetcode.com/problems/pairs-of-songs-with-total-durations-divisible-by-60", topic: "Array, Hash Table, Counting", difficulty: "Medium" },
  { id: 309, name: "Implement Queue Using Stacks", url: "https://leetcode.com/problems/implement-queue-using-stacks", topic: "Stack, Design, Queue", difficulty: "Easy" },
  { id: 310, name: "Maximum Xor Of Two Numbers In An Array", url: "https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array", topic: "Array, Hash Table, Bit Manipulation, Trie", difficulty: "Medium" },
  { id: 311, name: "Roman To Integer", url: "https://leetcode.com/problems/roman-to-integer", topic: "Hash Table, Math, String", difficulty: "Easy" },
  { id: 312, name: "Find The Town Judge", url: "https://leetcode.com/problems/find-the-town-judge", topic: "Array, Hash Table, Graph", difficulty: "Easy" },
  { id: 313, name: "Find K Pairs With Smallest Sums", url: "https://leetcode.com/problems/find-k-pairs-with-smallest-sums", topic: "Array, Heap (Priority Queue)", difficulty: "Medium" },
  { id: 314, name: "Merge Sorted Array", url: "https://leetcode.com/problems/merge-sorted-array", topic: "Array, Two Pointers, Sorting", difficulty: "Easy" },
  { id: 315, name: "Remove All Adjacent Duplicates In String", url: "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string", topic: "String, Stack", difficulty: "Easy" },
  { id: 316, name: "Reverse Words In A String", url: "https://leetcode.com/problems/reverse-words-in-a-string", topic: "Two Pointers, String", difficulty: "Medium" },
  { id: 317, name: "4sum Ii", url: "https://leetcode.com/problems/4sum-ii", topic: "Array, Hash Table", difficulty: "Medium" },
  { id: 318, name: "Average Of Levels In Binary Tree", url: "https://leetcode.com/problems/average-of-levels-in-binary-tree", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 319, name: "Find Pivot Index", url: "https://leetcode.com/problems/find-pivot-index", topic: "Array, Prefix Sum", difficulty: "Easy" },
  { id: 320, name: "How Many Numbers Are Smaller Than The Current Number", url: "https://leetcode.com/problems/how-many-numbers-are-smaller-than-the-current-number", topic: "Array, Hash Table, Sorting, Counting", difficulty: "Easy" },
  { id: 321, name: "Integer To Roman", url: "https://leetcode.com/problems/integer-to-roman", topic: "Hash Table, Math, String", difficulty: "Medium" },
  { id: 322, name: "Keys And Rooms", url: "https://leetcode.com/problems/keys-and-rooms", topic: "Depth-First Search, Breadth-First Search, Graph", difficulty: "Medium" },
  { id: 323, name: "Power Of Two", url: "https://leetcode.com/problems/power-of-two", topic: "Math, Bit Manipulation, Recursion", difficulty: "Easy" },
  { id: 324, name: "Subarrays With K Different Integers", url: "https://leetcode.com/problems/subarrays-with-k-different-integers", topic: "Array, Hash Table, Sliding Window, Counting", difficulty: "Hard" },
  { id: 325, name: "Predict The Winner", url: "https://leetcode.com/problems/predict-the-winner", topic: "Array, Math, Dynamic Programming, Recursion, Game Theory", difficulty: "Medium" },
  { id: 326, name: "Maximum Sum Circular Subarray", url: "https://leetcode.com/problems/maximum-sum-circular-subarray", topic: "Array, Divide and Conquer, Dynamic Programming, Queue, Monotonic Queue", difficulty: "Medium" },
  { id: 327, name: "Fibonacci Number", url: "https://leetcode.com/problems/fibonacci-number", topic: "Math, Dynamic Programming, Recursion, Memoization", difficulty: "Easy" },
  { id: 328, name: "Reverse Bits", url: "https://leetcode.com/problems/reverse-bits", topic: "Divide and Conquer, Bit Manipulation", difficulty: "Easy" },
  { id: 329, name: "Delete Nodes And Return Forest", url: "https://leetcode.com/problems/delete-nodes-and-return-forest", topic: "Tree, Depth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 330, name: "Shortest Subarray With Sum At Least K", url: "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k", topic: "Array, Binary Search, Queue, Sliding Window, Heap (Priority Queue), Prefix Sum, Monotonic Queue", difficulty: "Hard" },
  { id: 331, name: "Find Minimum In Rotated Sorted Array Ii", url: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array-ii", topic: "Array, Binary Search", difficulty: "Hard" },
  { id: 332, name: "Word Pattern", url: "https://leetcode.com/problems/word-pattern", topic: "Hash Table, String", difficulty: "Easy" },
  { id: 333, name: "Arithmetic Slices", url: "https://leetcode.com/problems/arithmetic-slices", topic: "Array, Dynamic Programming", difficulty: "Medium" },
  { id: 334, name: "Ones And Zeroes", url: "https://leetcode.com/problems/ones-and-zeroes", topic: "Array, String, Dynamic Programming", difficulty: "Medium" },
  { id: 335, name: "Unique Paths Iii", url: "https://leetcode.com/problems/unique-paths-iii", topic: "Array, Backtracking, Bit Manipulation, Matrix", difficulty: "Hard" },
  { id: 336, name: "Range Sum Query Mutable", url: "https://leetcode.com/problems/range-sum-query-mutable", topic: "Array, Design, Binary Indexed Tree, Segment Tree", difficulty: "Medium" },
  { id: 337, name: "Vertical Order Traversal Of A Binary Tree", url: "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree", topic: "Hash Table, Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Hard" },
  { id: 338, name: "Candy", url: "https://leetcode.com/problems/candy", topic: "Array, Greedy", difficulty: "Hard" },
  { id: 339, name: "Remove Duplicates From Sorted Array Ii", url: "https://leetcode.com/problems/remove-duplicates-from-sorted-array-ii", topic: "Array, Two Pointers", difficulty: "Medium" },
  { id: 340, name: "Number Of Matching Subsequences", url: "https://leetcode.com/problems/number-of-matching-subsequences", topic: "Hash Table, String, Trie, Sorting", difficulty: "Medium" },
  { id: 341, name: "Koko Eating Bananas", url: "https://leetcode.com/problems/koko-eating-bananas", topic: "Array, Binary Search", difficulty: "Medium" },
  { id: 342, name: "Open The Lock", url: "https://leetcode.com/problems/open-the-lock", topic: "Array, Hash Table, String, Breadth-First Search", difficulty: "Medium" },
  { id: 343, name: "Serialize And Deserialize Bst", url: "https://leetcode.com/problems/serialize-and-deserialize-bst", topic: "String, Tree, Depth-First Search, Breadth-First Search, Design, Binary Search Tree, Binary Tree", difficulty: "Medium" },
  { id: 344, name: "Combination Sum Iii", url: "https://leetcode.com/problems/combination-sum-iii", topic: "Array, Backtracking", difficulty: "Medium" },
  { id: 345, name: "Palindrome Pairs", url: "https://leetcode.com/problems/palindrome-pairs", topic: "Array, Hash Table, String, Trie", difficulty: "Hard" },
  { id: 346, name: "Verifying An Alien Dictionary", url: "https://leetcode.com/problems/verifying-an-alien-dictionary", topic: "Array, Hash Table, String", difficulty: "Easy" },
  { id: 347, name: "Evaluate Reverse Polish Notation", url: "https://leetcode.com/problems/evaluate-reverse-polish-notation", topic: "Array, Math, Stack", difficulty: "Medium" },
  { id: 348, name: "Trapping Rain Water Ii", url: "https://leetcode.com/problems/trapping-rain-water-ii", topic: "Array, Breadth-First Search, Heap (Priority Queue), Matrix", difficulty: "Hard" },
  { id: 349, name: "Maximum Points You Can Obtain From Cards", url: "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards", topic: "Array, Sliding Window, Prefix Sum", difficulty: "Medium" },
  { id: 350, name: "Cousins In Binary Tree", url: "https://leetcode.com/problems/cousins-in-binary-tree", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 351, name: "Divide Two Integers", url: "https://leetcode.com/problems/divide-two-integers", topic: "Math, Bit Manipulation", difficulty: "Medium" },
  { id: 352, name: "Delete Operation For Two Strings", url: "https://leetcode.com/problems/delete-operation-for-two-strings", topic: "String, Dynamic Programming", difficulty: "Medium" },
  { id: 353, name: "Minimum Number Of Arrows To Burst Balloons", url: "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons", topic: "Array, Greedy, Sorting", difficulty: "Medium" },
  { id: 354, name: "Subarray Sums Divisible By K", url: "https://leetcode.com/problems/subarray-sums-divisible-by-k", topic: "Array, Hash Table, Prefix Sum", difficulty: "Medium" },
  { id: 355, name: "Count Binary Substrings", url: "https://leetcode.com/problems/count-binary-substrings", topic: "Two Pointers, String", difficulty: "Easy" },
  { id: 356, name: "Restore Ip Addresses", url: "https://leetcode.com/problems/restore-ip-addresses", topic: "String, Backtracking", difficulty: "Medium" },
  { id: 357, name: "Spiral Matrix Ii", url: "https://leetcode.com/problems/spiral-matrix-ii", topic: "Array, Matrix, Simulation", difficulty: "Medium" },
  { id: 358, name: "Maximum Frequency Stack", url: "https://leetcode.com/problems/maximum-frequency-stack", topic: "Hash Table, Stack, Design, Ordered Set", difficulty: "Hard" },
  { id: 359, name: "Integer Break", url: "https://leetcode.com/problems/integer-break", topic: "Math, Dynamic Programming", difficulty: "Medium" },
  { id: 360, name: "Sort Array By Parity", url: "https://leetcode.com/problems/sort-array-by-parity", topic: "Array, Two Pointers, Sorting", difficulty: "Easy" },
  { id: 361, name: "Binary Tree Cameras", url: "https://leetcode.com/problems/binary-tree-cameras", topic: "Dynamic Programming, Tree, Depth-First Search, Binary Tree", difficulty: "Hard" },
  { id: 362, name: "Wiggle Subsequence", url: "https://leetcode.com/problems/wiggle-subsequence", topic: "Array, Dynamic Programming, Greedy", difficulty: "Medium" },
  { id: 363, name: "Jump Game Iii", url: "https://leetcode.com/problems/jump-game-iii", topic: "Array, Depth-First Search, Breadth-First Search", difficulty: "Medium" },
  { id: 364, name: "Number Of 1 Bits", url: "https://leetcode.com/problems/number-of-1-bits", topic: "Bit Manipulation", difficulty: "Easy" },
  { id: 365, name: "Insert Into A Binary Search Tree", url: "https://leetcode.com/problems/insert-into-a-binary-search-tree", topic: "Tree, Binary Search Tree, Binary Tree", difficulty: "Medium" },
  { id: 366, name: "Maximum Product Of Three Numbers", url: "https://leetcode.com/problems/maximum-product-of-three-numbers", topic: "Array, Math, Sorting", difficulty: "Easy" },
  { id: 367, name: "Expression Add Operators", url: "https://leetcode.com/problems/expression-add-operators", topic: "Math, String, Backtracking", difficulty: "Hard" },
  { id: 368, name: "Excel Sheet Column Title", url: "https://leetcode.com/problems/excel-sheet-column-title", topic: "Math, String", difficulty: "Easy" },
  { id: 369, name: "Reverse Pairs", url: "https://leetcode.com/problems/reverse-pairs", topic: "Array, Binary Search, Divide and Conquer, Binary Indexed Tree, Segment Tree, Merge Sort, Ordered Set", difficulty: "Hard" },
  { id: 370, name: "Sum Of Distances In Tree", url: "https://leetcode.com/problems/sum-of-distances-in-tree", topic: "Dynamic Programming, Tree, Depth-First Search, Graph", difficulty: "Hard" },
  { id: 371, name: "Two City Scheduling", url: "https://leetcode.com/problems/two-city-scheduling", topic: "Array, Greedy, Sorting", difficulty: "Medium" },
  { id: 372, name: "Remove All Adjacent Duplicates In String Ii", url: "https://leetcode.com/problems/remove-all-adjacent-duplicates-in-string-ii", topic: "String, Stack", difficulty: "Medium" },
  { id: 373, name: "Range Sum Query 2d Immutable", url: "https://leetcode.com/problems/range-sum-query-2d-immutable", topic: "Array, Design, Matrix, Prefix Sum", difficulty: "Medium" },
  { id: 374, name: "2 Keys Keyboard", url: "https://leetcode.com/problems/2-keys-keyboard", topic: "Math, Dynamic Programming", difficulty: "Medium" },
  { id: 375, name: "Intersection Of Two Arrays", url: "https://leetcode.com/problems/intersection-of-two-arrays", topic: "Array, Hash Table, Two Pointers, Binary Search, Sorting", difficulty: "Easy" },
  { id: 376, name: "Validate Stack Sequences", url: "https://leetcode.com/problems/validate-stack-sequences", topic: "Array, Stack, Simulation", difficulty: "Medium" },
  { id: 377, name: "Longest Palindrome", url: "https://leetcode.com/problems/longest-palindrome", topic: "Hash Table, String, Greedy", difficulty: "Easy" },
  { id: 378, name: "Search In A Binary Search Tree", url: "https://leetcode.com/problems/search-in-a-binary-search-tree", topic: "Tree, Binary Search Tree, Binary Tree", difficulty: "Easy" },
  { id: 379, name: "Minimum Number Of Refueling Stops", url: "https://leetcode.com/problems/minimum-number-of-refueling-stops", topic: "Array, Dynamic Programming, Greedy, Heap (Priority Queue)", difficulty: "Hard" },
  { id: 380, name: "Valid Triangle Number", url: "https://leetcode.com/problems/valid-triangle-number", topic: "Array, Two Pointers, Binary Search, Greedy, Sorting", difficulty: "Medium" },
  { id: 381, name: "All Possible Full Binary Trees", url: "https://leetcode.com/problems/all-possible-full-binary-trees", topic: "Dynamic Programming, Tree, Recursion, Memoization, Binary Tree", difficulty: "Medium" },
  { id: 382, name: "Reverse Words In A String Iii", url: "https://leetcode.com/problems/reverse-words-in-a-string-iii", topic: "Two Pointers, String", difficulty: "Easy" },
  { id: 383, name: "Excel Sheet Column Number", url: "https://leetcode.com/problems/excel-sheet-column-number", topic: "Math, String", difficulty: "Easy" },
  { id: 384, name: "Cherry Pickup", url: "https://leetcode.com/problems/cherry-pickup", topic: "Array, Dynamic Programming, Matrix", difficulty: "Hard" },
  { id: 385, name: "Design Hashmap", url: "https://leetcode.com/problems/design-hashmap", topic: "Array, Hash Table, Linked List, Design, Hash Function", difficulty: "Easy" },
  { id: 386, name: "Binary Tree Pruning", url: "https://leetcode.com/problems/binary-tree-pruning", topic: "Tree, Depth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 387, name: "Sum Of Two Integers", url: "https://leetcode.com/problems/sum-of-two-integers", topic: "Math, Bit Manipulation", difficulty: "Medium" },
  { id: 388, name: "Online Stock Span", url: "https://leetcode.com/problems/online-stock-span", topic: "Stack, Design, Monotonic Stack, Data Stream", difficulty: "Medium" },
  { id: 389, name: "Convert Binary Number In A Linked List To Integer", url: "https://leetcode.com/problems/convert-binary-number-in-a-linked-list-to-integer", topic: "Linked List, Math", difficulty: "Easy" },
  { id: 390, name: "Binary Search Tree To Greater Sum Tree", url: "https://leetcode.com/problems/binary-search-tree-to-greater-sum-tree", topic: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", difficulty: "Medium" },
  { id: 391, name: "Max Consecutive Ones", url: "https://leetcode.com/problems/max-consecutive-ones", topic: "Array", difficulty: "Easy" },
  { id: 392, name: "Running Sum Of 1d Array", url: "https://leetcode.com/problems/running-sum-of-1d-array", topic: "Array, Prefix Sum", difficulty: "Easy" },
  { id: 393, name: "Maximum Swap", url: "https://leetcode.com/problems/maximum-swap", topic: "Math, Greedy", difficulty: "Medium" },
  { id: 394, name: "Shortest Palindrome", url: "https://leetcode.com/problems/shortest-palindrome", topic: "String, Rolling Hash, String Matching, Hash Function", difficulty: "Hard" },
  { id: 395, name: "Most Stones Removed With Same Row Or Column", url: "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column", topic: "Depth-First Search, Union Find, Graph", difficulty: "Medium" },
  { id: 396, name: "Maximum Difference Between Node And Ancestor", url: "https://leetcode.com/problems/maximum-difference-between-node-and-ancestor", topic: "Tree, Depth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 397, name: "Frog Jump", url: "https://leetcode.com/problems/frog-jump", topic: "Array, Dynamic Programming", difficulty: "Hard" },
  { id: 398, name: "Pascals Triangle Ii", url: "https://leetcode.com/problems/pascals-triangle-ii", topic: "Array, Dynamic Programming", difficulty: "Easy" },
  { id: 399, name: "Deepest Leaves Sum", url: "https://leetcode.com/problems/deepest-leaves-sum", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 400, name: "Shortest Bridge", url: "https://leetcode.com/problems/shortest-bridge", topic: "Array, Depth-First Search, Breadth-First Search, Matrix", difficulty: "Medium" },
  { id: 401, name: "Bitwise And Of Numbers Range", url: "https://leetcode.com/problems/bitwise-and-of-numbers-range", topic: "Bit Manipulation", difficulty: "Medium" },
  { id: 402, name: "Super Egg Drop", url: "https://leetcode.com/problems/super-egg-drop", topic: "Math, Binary Search, Dynamic Programming", difficulty: "Hard" },
  { id: 403, name: "Contains Duplicate Iii", url: "https://leetcode.com/problems/contains-duplicate-iii", topic: "Array, Sliding Window, Sorting, Bucket Sort, Ordered Set", difficulty: "Medium" },
  { id: 404, name: "Robot Bounded In Circle", url: "https://leetcode.com/problems/robot-bounded-in-circle", topic: "Math, String, Simulation", difficulty: "Medium" },
  { id: 405, name: "Increasing Order Search Tree", url: "https://leetcode.com/problems/increasing-order-search-tree", topic: "Stack, Tree, Depth-First Search, Binary Search Tree, Binary Tree", difficulty: "Easy" },
  { id: 406, name: "Find Common Characters", url: "https://leetcode.com/problems/find-common-characters", topic: "Array, Hash Table, String", difficulty: "Easy" },
  { id: 407, name: "Shortest Distance To A Character", url: "https://leetcode.com/problems/shortest-distance-to-a-character", topic: "Array, Two Pointers, String", difficulty: "Easy" },
  { id: 408, name: "Can Place Flowers", url: "https://leetcode.com/problems/can-place-flowers", topic: "Array, Greedy", difficulty: "Easy" },
  { id: 409, name: "Contains Duplicate Ii", url: "https://leetcode.com/problems/contains-duplicate-ii", topic: "Array, Hash Table, Sliding Window", difficulty: "Easy" },
  { id: 410, name: "Number Of Good Pairs", url: "https://leetcode.com/problems/number-of-good-pairs", topic: "Array, Hash Table, Math, Counting", difficulty: "Easy" },
  { id: 411, name: "Minimum Add To Make Parentheses Valid", url: "https://leetcode.com/problems/minimum-add-to-make-parentheses-valid", topic: "String, Stack, Greedy", difficulty: "Medium" },
  { id: 412, name: "Maximum Length Of Pair Chain", url: "https://leetcode.com/problems/maximum-length-of-pair-chain", topic: "Array, Dynamic Programming, Greedy, Sorting", difficulty: "Medium" },
  { id: 413, name: "Possible Bipartition", url: "https://leetcode.com/problems/possible-bipartition", topic: "Depth-First Search, Breadth-First Search, Union Find, Graph", difficulty: "Medium" },
  { id: 414, name: "Split Array Into Consecutive Subsequences", url: "https://leetcode.com/problems/split-array-into-consecutive-subsequences", topic: "Array, Hash Table, Greedy, Heap (Priority Queue)", difficulty: "Medium" },
  { id: 415, name: "Making A Large Island", url: "https://leetcode.com/problems/making-a-large-island", topic: "Array, Depth-First Search, Breadth-First Search, Union Find, Matrix", difficulty: "Hard" },
  { id: 416, name: "Shortest Path In Binary Matrix", url: "https://leetcode.com/problems/shortest-path-in-binary-matrix", topic: "Array, Breadth-First Search, Matrix", difficulty: "Medium" },
  { id: 417, name: "Count Good Nodes In Binary Tree", url: "https://leetcode.com/problems/count-good-nodes-in-binary-tree", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 418, name: "Shuffle The Array", url: "https://leetcode.com/problems/shuffle-the-array", topic: "Array", difficulty: "Easy" },
  { id: 419, name: "Sliding Window Median", url: "https://leetcode.com/problems/sliding-window-median", topic: "Array, Hash Table, Sliding Window, Heap (Priority Queue)", difficulty: "Hard" },
  { id: 420, name: "Kth Missing Positive Number", url: "https://leetcode.com/problems/kth-missing-positive-number", topic: "Array, Binary Search", difficulty: "Easy" },
  { id: 421, name: "Peak Index In A Mountain Array", url: "https://leetcode.com/problems/peak-index-in-a-mountain-array", topic: "Array, Binary Search", difficulty: "Easy" },
  { id: 422, name: "Next Greater Node In Linked List", url: "https://leetcode.com/problems/next-greater-node-in-linked-list", topic: "Array, Linked List, Stack, Monotonic Stack", difficulty: "Medium" },
  { id: 423, name: "Minimum Swaps To Make Sequences Increasing", url: "https://leetcode.com/problems/minimum-swaps-to-make-sequences-increasing", topic: "Array, Dynamic Programming", difficulty: "Hard" },
  { id: 424, name: "Wiggle Sort Ii", url: "https://leetcode.com/problems/wiggle-sort-ii", topic: "Array, Divide and Conquer, Sorting, Quickselect", difficulty: "Medium" },
  { id: 425, name: "Smallest Range Covering Elements From K Lists", url: "https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists", topic: "Array, Hash Table, Greedy, Sliding Window, Sorting, Heap (Priority Queue)", difficulty: "Hard" },
  { id: 426, name: "Integer To English Words", url: "https://leetcode.com/problems/integer-to-english-words", topic: "Math, String, Recursion", difficulty: "Hard" },
  { id: 427, name: "Partition Array For Maximum Sum", url: "https://leetcode.com/problems/partition-array-for-maximum-sum", topic: "Array, Dynamic Programming", difficulty: "Medium" },
  { id: 428, name: "Maximum Gap", url: "https://leetcode.com/problems/maximum-gap", topic: "Array, Sorting, Bucket Sort, Radix Sort", difficulty: "Hard" },
  { id: 429, name: "Find Mode In Binary Search Tree", url: "https://leetcode.com/problems/find-mode-in-binary-search-tree", topic: "Tree, Depth-First Search, Binary Search Tree, Binary Tree", difficulty: "Easy" },
  { id: 430, name: "Longest Arithmetic Subsequence", url: "https://leetcode.com/problems/longest-arithmetic-subsequence", topic: "Array, Hash Table, Binary Search, Dynamic Programming", difficulty: "Medium" },
  { id: 431, name: "Last Stone Weight Ii", url: "https://leetcode.com/problems/last-stone-weight-ii", topic: "Array, Dynamic Programming", difficulty: "Medium" },
  { id: 432, name: "Last Stone Weight", url: "https://leetcode.com/problems/last-stone-weight", topic: "Array, Heap (Priority Queue)", difficulty: "Easy" },
  { id: 433, name: "Find Bottom Left Tree Value", url: "https://leetcode.com/problems/find-bottom-left-tree-value", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 434, name: "Regions Cut By Slashes", url: "https://leetcode.com/problems/regions-cut-by-slashes", topic: "Depth-First Search, Breadth-First Search, Union Find, Graph", difficulty: "Medium" },
  { id: 435, name: "Beautiful Arrangement", url: "https://leetcode.com/problems/beautiful-arrangement", topic: "Array, Dynamic Programming, Backtracking, Bit Manipulation, Bitmask", difficulty: "Medium" },
  { id: 436, name: "Minimum Falling Path Sum", url: "https://leetcode.com/problems/minimum-falling-path-sum", topic: "Array, Dynamic Programming, Matrix", difficulty: "Medium" },
  { id: 437, name: "Diagonal Traverse", url: "https://leetcode.com/problems/diagonal-traverse", topic: "Array, Matrix, Simulation", difficulty: "Medium" },
  { id: 438, name: "Longest Continuous Subarray With Absolute Diff Less Than Or Equal To Limit", url: "https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit", topic: "Array, Queue, Sliding Window, Heap (Priority Queue), Ordered Set, Monotonic Queue", difficulty: "Medium" },
  { id: 439, name: "Number Complement", url: "https://leetcode.com/problems/number-complement", topic: "Bit Manipulation", difficulty: "Easy" },
  { id: 440, name: "Valid Perfect Square", url: "https://leetcode.com/problems/valid-perfect-square", topic: "Math, Binary Search", difficulty: "Easy" },
  { id: 441, name: "Arranging Coins", url: "https://leetcode.com/problems/arranging-coins", topic: "Math, Binary Search", difficulty: "Easy" },
  { id: 442, name: "Next Greater Element Iii", url: "https://leetcode.com/problems/next-greater-element-iii", topic: "Math, Two Pointers, String", difficulty: "Medium" },
  { id: 443, name: "Path With Minimum Effort", url: "https://leetcode.com/problems/path-with-minimum-effort", topic: "Array, Binary Search, Depth-First Search, Breadth-First Search, Union Find, Heap (Priority Queue), Matrix", difficulty: "Medium" },
  { id: 444, name: "Search Suggestions System", url: "https://leetcode.com/problems/search-suggestions-system", topic: "Array, String, Trie", difficulty: "Medium" },
  { id: 445, name: "Flipping An Image", url: "https://leetcode.com/problems/flipping-an-image", topic: "Array, Two Pointers, Matrix, Simulation", difficulty: "Easy" },
  { id: 446, name: "Kth Largest Element In A Stream", url: "https://leetcode.com/problems/kth-largest-element-in-a-stream", topic: "Tree, Design, Binary Search Tree, Heap (Priority Queue), Binary Tree, Data Stream", difficulty: "Easy" },
  { id: 447, name: "Max Sum Of Rectangle No Larger Than K", url: "https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k", topic: "Array, Binary Search, Dynamic Programming, Matrix, Ordered Set", difficulty: "Hard" },
  { id: 448, name: "Time Based Key Value Store", url: "https://leetcode.com/problems/time-based-key-value-store", topic: "Hash Table, String, Binary Search, Design", difficulty: "Medium" },
  { id: 449, name: "Insertion Sort List", url: "https://leetcode.com/problems/insertion-sort-list", topic: "Linked List, Sorting", difficulty: "Medium" },
  { id: 450, name: "String Compression", url: "https://leetcode.com/problems/string-compression", topic: "Two Pointers, String", difficulty: "Medium" },
  { id: 451, name: "Maximum Depth Of N Ary Tree", url: "https://leetcode.com/problems/maximum-depth-of-n-ary-tree", topic: "Tree, Depth-First Search, Breadth-First Search", difficulty: "Easy" },
  { id: 452, name: "Factorial Trailing Zeroes", url: "https://leetcode.com/problems/factorial-trailing-zeroes", topic: "Math", difficulty: "Medium" },
  { id: 453, name: "Car Pooling", url: "https://leetcode.com/problems/car-pooling", topic: "Array, Sorting, Heap (Priority Queue), Simulation, Prefix Sum", difficulty: "Medium" },
  { id: 454, name: "Find Largest Value In Each Tree Row", url: "https://leetcode.com/problems/find-largest-value-in-each-tree-row", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 455, name: "Shortest Common Supersequence", url: "https://leetcode.com/problems/shortest-common-supersequence", topic: "String, Dynamic Programming", difficulty: "Hard" },
  { id: 456, name: "Number Of Dice Rolls With Target Sum", url: "https://leetcode.com/problems/number-of-dice-rolls-with-target-sum", topic: "Dynamic Programming", difficulty: "Medium" },
  { id: 457, name: "Design Twitter", url: "https://leetcode.com/problems/design-twitter", topic: "Hash Table, Linked List, Design, Heap (Priority Queue)", difficulty: "Medium" },
  { id: 458, name: "Array Nesting", url: "https://leetcode.com/problems/array-nesting", topic: "Array, Depth-First Search", difficulty: "Medium" },
  { id: 459, name: "Stone Game", url: "https://leetcode.com/problems/stone-game", topic: "Array, Math, Dynamic Programming, Game Theory", difficulty: "Medium" },
  { id: 460, name: "Degree Of An Array", url: "https://leetcode.com/problems/degree-of-an-array", topic: "Array, Hash Table", difficulty: "Easy" },
  { id: 461, name: "Find The Difference", url: "https://leetcode.com/problems/find-the-difference", topic: "Hash Table, String, Bit Manipulation, Sorting", difficulty: "Easy" },
  { id: 462, name: "Minimum Absolute Difference In Bst", url: "https://leetcode.com/problems/minimum-absolute-difference-in-bst", topic: "Tree, Depth-First Search, Breadth-First Search, Binary Search Tree, Binary Tree", difficulty: "Easy" },
  { id: 463, name: "Count Negative Numbers In A Sorted Matrix", url: "https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix", topic: "Array, Binary Search, Matrix", difficulty: "Easy" },
  { id: 464, name: "Course Schedule Iii", url: "https://leetcode.com/problems/course-schedule-iii", topic: "Array, Greedy, Heap (Priority Queue)", difficulty: "Hard" },
  { id: 465, name: "Smallest Subtree With All The Deepest Nodes", url: "https://leetcode.com/problems/smallest-subtree-with-all-the-deepest-nodes", topic: "Hash Table, Tree, Depth-First Search, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 466, name: "Reshape The Matrix", url: "https://leetcode.com/problems/reshape-the-matrix", topic: "Array, Matrix, Simulation", difficulty: "Easy" },
  { id: 467, name: "Toeplitz Matrix", url: "https://leetcode.com/problems/toeplitz-matrix", topic: "Array, Matrix", difficulty: "Easy" },
  { id: 468, name: "Knight Probability In Chessboard", url: "https://leetcode.com/problems/knight-probability-in-chessboard", topic: "Dynamic Programming", difficulty: "Medium" },
  { id: 469, name: "Find K Th Smallest Pair Distance", url: "https://leetcode.com/problems/find-k-th-smallest-pair-distance", topic: "Array, Two Pointers, Binary Search, Sorting", difficulty: "Hard" },
  { id: 470, name: "My Calendar I", url: "https://leetcode.com/problems/my-calendar-i", topic: "Design, Segment Tree, Ordered Set", difficulty: "Medium" },
  { id: 471, name: "Minimum Ascii Delete Sum For Two Strings", url: "https://leetcode.com/problems/minimum-ascii-delete-sum-for-two-strings", topic: "String, Dynamic Programming", difficulty: "Medium" },
  { id: 472, name: "Shortest Path In A Grid With Obstacles Elimination", url: "https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination", topic: "Array, Breadth-First Search, Matrix", difficulty: "Hard" },
  { id: 473, name: "Range Sum Query Immutable", url: "https://leetcode.com/problems/range-sum-query-immutable", topic: "Array, Design, Prefix Sum", difficulty: "Easy" },
  { id: 474, name: "Check Completeness Of A Binary Tree", url: "https://leetcode.com/problems/check-completeness-of-a-binary-tree", topic: "Tree, Breadth-First Search, Binary Tree", difficulty: "Medium" },
  { id: 475, name: "Maximize Distance To Closest Person", url: "https://leetcode.com/problems/maximize-distance-to-closest-person", topic: "Array", difficulty: "Medium" },
  { id: 476, name: "Implement Stack Using Queues", url: "https://leetcode.com/problems/implement-stack-using-queues", topic: "Stack, Design, Queue", difficulty: "Easy" },
  { id: 477, name: "Can I Win", url: "https://leetcode.com/problems/can-i-win", topic: "Math, Dynamic Programming, Bit Manipulation, Memoization, Game Theory, Bitmask", difficulty: "Medium" },
  { id: 478, name: "Custom Sort String", url: "https://leetcode.com/problems/custom-sort-string", topic: "Hash Table, String, Sorting", difficulty: "Medium" },
  { id: 479, name: "Brick Wall", url: "https://leetcode.com/problems/brick-wall", topic: "Array, Hash Table", difficulty: "Medium" },
  { id: 480, name: "Next Greater Element I", url: "https://leetcode.com/problems/next-greater-element-i", topic: "Array, Hash Table, Stack, Monotonic Stack", difficulty: "Easy" },
  { id: 481, name: "Sum Of Root To Leaf Binary Numbers", url: "https://leetcode.com/problems/sum-of-root-to-leaf-binary-numbers", topic: "Tree, Depth-First Search, Binary Tree", difficulty: "Easy" },
  { id: 482, name: "Find Eventual Safe States", url: "https://leetcode.com/problems/find-eventual-safe-states", topic: "Depth-First Search, Breadth-First Search, Graph, Topological Sort", difficulty: "Medium" },
  { id: 483, name: "Reveal Cards In Increasing Order", url: "https://leetcode.com/problems/reveal-cards-in-increasing-order", topic: "Array, Queue, Sorting, Simulation", difficulty: "Medium" },
  { id: 484, name: "Concatenated Words", url: "https://leetcode.com/problems/concatenated-words", topic: "Array, String, Dynamic Programming, Depth-First Search, Trie", difficulty: "Hard" },
  { id: 485, name: "Boats To Save People", url: "https://leetcode.com/problems/boats-to-save-people", topic: "Array, Two Pointers, Greedy, Sorting", difficulty: "Medium" },
  { id: 486, name: "Construct Binary Tree From Preorder And Postorder Traversal", url: "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-postorder-traversal", topic: "Array, Hash Table, Divide and Conquer, Tree, Binary Tree", difficulty: "Medium" },
  { id: 487, name: "Count Number Of Teams", url: "https://leetcode.com/problems/count-number-of-teams", topic: "Array, Dynamic Programming, Binary Indexed Tree", difficulty: "Medium" },
  { id: 488, name: "Repeated Dna Sequences", url: "https://leetcode.com/problems/repeated-dna-sequences", topic: "Hash Table, String, Bit Manipulation, Sliding Window, Rolling Hash, Hash Function", difficulty: "Medium" },
  { id: 489, name: "Substring With Concatenation Of All Words", url: "https://leetcode.com/problems/substring-with-concatenation-of-all-words", topic: "Hash Table, String, Sliding Window", difficulty: "Hard" },
  { id: 490, name: "Bus Routes", url: "https://leetcode.com/problems/bus-routes", topic: "Array, Hash Table, Breadth-First Search", difficulty: "Hard" },
  { id: 491, name: "Find And Replace Pattern", url: "https://leetcode.com/problems/find-and-replace-pattern", topic: "Array, Hash Table, String", difficulty: "Medium" },
  { id: 492, name: "Swim In Rising Water", url: "https://leetcode.com/problems/swim-in-rising-water", topic: "Array, Binary Search, Depth-First Search, Breadth-First Search, Union Find, Heap (Priority Queue), Matrix", difficulty: "Hard" },
  { id: 493, name: "Number Of Operations To Make Network Connected", url: "https://leetcode.com/problems/number-of-operations-to-make-network-connected", topic: "Depth-First Search, Breadth-First Search, Union Find, Graph", difficulty: "Medium" },
  { id: 494, name: "Sort An Array", url: "https://leetcode.com/problems/sort-an-array", topic: "Array, Divide and Conquer, Sorting, Heap (Priority Queue), Merge Sort, Bucket Sort, Radix Sort, Counting Sort", difficulty: "Medium" },
  { id: 495, name: "Path With Maximum Gold", url: "https://leetcode.com/problems/path-with-maximum-gold", topic: "Array, Backtracking, Matrix", difficulty: "Medium" },
  { id: 496, name: "Set Mismatch", url: "https://leetcode.com/problems/set-mismatch", topic: "Array, Hash Table, Bit Manipulation, Sorting", difficulty: "Easy" },
  { id: 497, name: "Split Linked List In Parts", url: "https://leetcode.com/problems/split-linked-list-in-parts", topic: "Linked List", difficulty: "Medium" },
  { id: 498, name: "Longest Mountain In Array", url: "https://leetcode.com/problems/longest-mountain-in-array", topic: "Array, Two Pointers, Dynamic Programming, Enumeration", difficulty: "Medium" },
  { id: 499, name: "Rotate String", url: "https://leetcode.com/problems/rotate-string", topic: "String, String Matching", difficulty: "Easy" },
  { id: 500, name: "Unique Email Addresses", url: "https://leetcode.com/problems/unique-email-addresses", topic: "Array, Hash Table, String", difficulty: "Easy" },
];

// Generate remaining 400 problems from the CSV data
// Topics for categorization
export const CTCI_TOPICS = [
  "Array", "String", "Dynamic Programming", "Tree", "Graph",
  "Linked List", "Binary Search", "Stack", "Hash Table",
  "Backtracking", "Greedy", "Heap (Priority Queue)", "Bit Manipulation",
  "Two Pointers", "Sliding Window", "Matrix", "Math", "Design"
];

export const DIFFICULTY_COLORS = {
  Easy: { bg: 'bg-emerald-100 dark:bg-emerald-900/30', text: 'text-emerald-700 dark:text-emerald-400', border: 'border-emerald-200 dark:border-emerald-800' },
  Medium: { bg: 'bg-amber-100 dark:bg-amber-900/30', text: 'text-amber-700 dark:text-amber-400', border: 'border-amber-200 dark:border-amber-800' },
  Hard: { bg: 'bg-red-100 dark:bg-red-900/30', text: 'text-red-700 dark:text-red-400', border: 'border-red-200 dark:border-red-800' },
};
